/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as BoardsBoardIdEditRouteImport } from './routes/boards.$boardId.edit'
import { Route as BoardsBoardIdPlayRouteImport } from './routes/boards.$boardId.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdEditRoute = BoardsBoardIdEditRouteImport.update({
  id: '/boards/$boardId/edit',
  path: '/boards/$boardId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdPlayRoute = BoardsBoardIdPlayRouteImport.update({
  id: '/boards/$boardId/play',
  path: '/boards/$boardId/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
  '/boards/$boardId/play': typeof BoardsBoardIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
  '/boards/$boardId/play': typeof BoardsBoardIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
  '/boards/$boardId/play': typeof BoardsBoardIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/join' | '/boards/$boardId/edit' | '/boards/$boardId/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/join' | '/boards/$boardId/edit' | '/boards/$boardId/play'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/boards/$boardId/edit'
    | '/boards/$boardId/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  BoardsBoardIdEditRoute: typeof BoardsBoardIdEditRoute
  BoardsBoardIdPlayRoute: typeof BoardsBoardIdPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId/edit': {
      id: '/boards/$boardId/edit'
      path: '/boards/$boardId/edit'
      fullPath: '/boards/$boardId/edit'
      preLoaderRoute: typeof BoardsBoardIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId/play': {
      id: '/boards/$boardId/play'
      path: '/boards/$boardId/play'
      fullPath: '/boards/$boardId/play'
      preLoaderRoute: typeof BoardsBoardIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  BoardsBoardIdEditRoute: BoardsBoardIdEditRoute,
  BoardsBoardIdPlayRoute: BoardsBoardIdPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
